import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  docs: [
    {
      type: "category",
      label: "Memo",
      link: {
        type: "generated-index",
        slug: "/memo",
      },
      items: [{ type: "autogenerated", dirName: "memo" }],
    },
    {
      type: "category",
      label: "Misc",
      link: {
        type: "generated-index",
        title: "Misc",
        slug: "/misc",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "misc",
        },
      ],
    },
  ],
};

export default sidebars;
